import mongoose from "mongoose";

const PropertySchema = new mongoose.Schema(
  {
    responsibleForCouncilTax: {
      type: String,
      enum: [" RSL/Housing provider", "Tenant"],
      required: true,
    },
    rslTypeGroup: { type: String, required: true },
    address: { type: String, required: true },
    noOfBedrooms: { type: Number, required: true },
    area: { type: String, required: true },
    city: { type: String, required: true },
    postCode: { type: String, required: true },
    basicRent: { type: Number, required: true },
    totalServiceCharges: { type: Number, required: true },
    totalEligibleRent: { type: Number, required: true },
    weeklyIneligibleCharge: { type: Number, required: true },
    sharedWithOther: { type: Boolean, default: false },
    bedsit: { type: Boolean, default: false },
    selfContainedFlat: { type: Boolean, default: false },
    quantityOfFloors: { type: Number, required: true },
    unfurnished: { type: Boolean, default: false },
    partFurnished: { type: Boolean, default: false },
    fullyFurnished: { type: Boolean, default: false },
    centralHeating: { type: Boolean, default: false },
    garden: { type: Boolean, default: false },
    garageParkingSpace: { type: Boolean, default: false },
    accommodationLocation: { type: String },
    accommodationFloor: { type: String },
    totalLivingRooms: { type: Number, default: 0 },
    livingRoomsYourUse: { type: Number, default: 0 },
    livingRoomsCommunal: { type: Number, default: 0 },
    totalBedsitRooms: { type: Number, default: 0 },
    bedsitYourUse: { type: Number, default: 0 },
    bedsitCommunal: { type: Number, default: 0 },
    totalBedrooms: { type: Number, default: 0 },
    bedroomsYourUse: { type: Number, default: 0 },
    bedroomsCommunal: { type: Number, default: 0 },
    totalBathrooms: { type: Number, default: 0 },
    bathroomsYourUse: { type: Number, default: 0 },
    bathroomsCommunal: { type: Number, default: 0 },
    totalToilets: { type: Number, default: 0 },
    toiletsYourUse: { type: Number, default: 0 },
    toiletsCommunal: { type: Number, default: 0 },
    totalKitchens: { type: Number, default: 0 },
    kitchensYourUse: { type: Number, default: 0 },
    kitchensCommunal: { type: Number, default: 0 },
    totalOtherRooms: { type: Number, default: 0 },
    otherRoomsYourUse: { type: Number, default: 0 },
    otherRoomsCommunal: { type: Number, default: 0 },
    addedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    isDeleted: { type: Boolean, default: false },
    status: { type: Number, default: 1 },
  },
  { timestamps: true }
);

const Property = mongoose.model("Property", PropertySchema);
export default Property;
